train:
  _target_: src.datasets.Dataset
  part: "train"
  data_dir: "dla_dataset/dla_dataset"
  instance_transforms:
    _target_: src.transforms.audio_augment.InstanceTransforms
    is_train: true
    target_length: 48000  
val:
  _target_: src.datasets.Dataset
  part: "val"
  data_dir: "dla_dataset/dla_dataset"
  instance_transforms:
    _target_: src.transforms.audio_augment.InstanceTransforms
    is_train: false
    target_length: 48000
test:
  _target_: src.datasets.Dataset
  part: "test"
  data_dir: "dla_dataset/dla_dataset"
  instance_transforms: null
