test:
  _target_: src.datasets.Dataset
  part: "test"
  data_dir: "dla_dataset"
  instance_transforms:
    _target_: src.transforms.audio_augment.InstanceTransforms
    is_train: false
    target_length: 48000
