defaults:
  - model: rtfsnet
  - metrics: base
  - datasets: custom_dir
  - dataloader: example
  - transforms: audio_separation
  - _self_
inferencer:
  device_tensors: ["mix", "source", "video"]
  device: auto
  save_path: "inference_custom_dir"
  seed: 1
  from_pretrained: "saved/testing/model_best.pth"
