_target_: src.logger.CometMLWriter
project_name: "pytorch_template"
workspace: null
run_name: "testing"
mode: "online"
loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: True # log checkpoints (including best) to CometML
id_length: 32 # length of the run_id
